language: python
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.5
git:
  lfs_skip_smudge: true
env:
  global:
    - STRATUMPASSWORD=BeMyDataBaePostGis!
    - PGDATABASE=gis
before_install: 
  # running out of WAL unless we reallocate 50 pct of VM to /var/ramfs
  - sudo mount -o remount,size=50% /var/ramfs
install:
  - git clone https://github.com/mattyschell/stratum.git
  - chmod +x ./stratum/sample_users.sh
  - chmod +x ./stratum/sample_schema.sh
  - psql -U postgres -c "create database $PGDATABASE"
  - "./stratum/sample_users.sh"
  - "(export PGPASSWORD=$STRATUMPASSWORD && ./stratum/sample_schema.sh)"
before_script:
  - chmod +x import.sh
  - chmod +x src/test/run_all_tests.sh
  - wget -O building.sql.gz https://github.com/mattyschell/stratum_bldg/raw/master/building.sql.gz
  - df -h
script:
  - "(export PGPASSWORD=$STRATUMPASSWORD && ./import.sh bldg_blue)"
  - df -h
  - "./src/test/run_all_tests.sh bldg_blue"
